name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
        
    - name: Build with Nuitka
      run: |
        python -m nuitka --standalone --windows-icon-from-ico=icon.ico --enable-plugin=pyside6 --windows-disable-console --assume-yes-for-downloads --show-progress --output-dir=build ambidex.py
        
    - name: Copy icon
      run: |
        copy icon.ico build\\ambidex.dist\\icon.ico
      
    - name: Upload built application
      uses: actions/upload-artifact@v4
      with:
        name: ambidex-app
        path: build/ambidex.dist/
        
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/ambidex.dist/ambidex.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
